### ISSUE TITLE
Player sometimes starts inside maze block

### ISSUE THREAD

**Issue by Ernest314** [summer-game-project/pengo#5]
Player spawn point is currently fixed at the center grid. Ideally it should spawn in a randomized, valid (empty) location.

**Comment by Ernest314** [comment]
Code refactoring has accidentally commented out your fix... ;)

**Comment by Ernest314** [comment]
I LIED

**Comment by Ernest314** [comment]
3rd time's the charm

**Comment by Ernest314** [comment]
I give up

**Comment by gravyonbread** [comment]
minor adjustment from before. Other than that, pretty much same implementation as the first time this  as closed
